s='Tops Technologies'

print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.center(40,"*"))
print(s.count("o"))
print(s.endswith("ese"))
print(s.startswith("to"))
print(s.find("log"))
print(s.index("T",3))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print("python program".title())
print(" ".isspace())
print("   Tops   ".strip())
print(s.swapcase())
